#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : usrbinvi
Version  : 2
Release  : 3
URL      : http://localhost/cgit/projects/usrbinvi/snapshot/usrbinvi-2.tar.xz
Source0  : http://localhost/cgit/projects/usrbinvi/snapshot/usrbinvi-2.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: usrbinvi-bin = %{version}-%{release}
Requires: usrbinvi-license = %{version}-%{release}

%description
No detailed description available

%package bin
Summary: bin components for the usrbinvi package.
Group: Binaries
Requires: usrbinvi-license = %{version}-%{release}

%description bin
bin components for the usrbinvi package.


%package license
Summary: license components for the usrbinvi package.
Group: Default

%description license
license components for the usrbinvi package.


%prep
%setup -q -n usrbinvi-2
cd %{_builddir}/usrbinvi-2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1619061689
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%autogen --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1619061689
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/usrbinvi
cp %{_builddir}/usrbinvi-2/COPYING.Apache-2.0 %{buildroot}/usr/share/package-licenses/usrbinvi/2b8b815229aa8a61e483fb4ba0588b8b6c491890
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/vi

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/usrbinvi/2b8b815229aa8a61e483fb4ba0588b8b6c491890
